"""Create users and documents tables

Revision ID: 5a5fa9d6172d
Revises: 
Create Date: 2025-06-22 22:35:01.216895

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5a5fa9d6172d'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('auth0_user_id', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('role', sa.Enum('doctor', 'patient', name='user_role'), nullable=False),
    sa.Column('date_of_birth', sa.DateTime(), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('doctor_id', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("(role = 'doctor' AND doctor_id IS NULL) OR (role = 'patient' AND doctor_id IS NOT NULL)", name='check_doctor_patient_constraint'),
    sa.ForeignKeyConstraint(['doctor_id'], ['users.auth0_user_id'], ),
    sa.PrimaryKeyConstraint('auth0_user_id'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_users_doctor_id'), 'users', ['doctor_id'], unique=False)
    op.create_table('documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('file_path', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('patient_id', sa.String(length=255), nullable=False),
    sa.Column('uploaded_by_id', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['users.auth0_user_id'], ),
    sa.ForeignKeyConstraint(['uploaded_by_id'], ['users.auth0_user_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_documents_patient_id'), 'documents', ['patient_id'], unique=False)
    op.create_index(op.f('ix_documents_uploaded_by_id'), 'documents', ['uploaded_by_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_documents_uploaded_by_id'), table_name='documents')
    op.drop_index(op.f('ix_documents_patient_id'), table_name='documents')
    op.drop_table('documents')
    op.drop_index(op.f('ix_users_doctor_id'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
