"""add_content_type_to_documents

Revision ID: 88cb61d1df10
Revises: b09f2e9fc5b9
Create Date: 2025-06-23 22:24:35.804370

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '88cb61d1df10'
down_revision: Union[str, None] = 'b09f2e9fc5b9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('content_type', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'content_type')
    # ### end Alembic commands ###
